import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import { FontProvider } from "@/context/font-provider";

import { QueryProvider } from "@/context/query-provider";
import { DirectionProvider } from "@/context/direction-provider";
import ToastProvider from "@/context/toast-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider>
            <FontProvider>
              <DirectionProvider >
                <ToastProvider />
                {children}
              </DirectionProvider>
            </FontProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
